version: '3.8'

services:
  procesiranje:
    build:
      context: ./Procesiranje_podatkov      
    volumes:
      - ./Procesiranje_podatkov/data:/app/data
      - ./shared_data:/app/shared_data
    working_dir: /app
    command: >
      python preprocess.py
        --input data/FRI_SR_WL.xlsx
        --sheet1 SR
        --sheet2 WL
        --output shared_data/df_no_nan_img.csv

  ml_api:
    build:
      context: ./ML_api
    ports:
      - "8000:8000"
    environment:
      - DATA_PATH=/app/shared_data/df_no_nan_img.csv
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PWHASH=${ADMIN_PWHASH}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8000
    volumes:
      - ./shared_data:/app/shared_data
    depends_on:
      - procesiranje

  backend:
    build:
      context: ./Backend
    ports:
      - "5100:5100"
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PWHASH=${ADMIN_PWHASH}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5100
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - ml_api
    volumes:
      - ./shared_data:/shared_data

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3000  # to bo uporabil nginx proxy
    depends_on:
      - backend